### ISSUE TITLE
./demo.sh start 报错 120秒超时怎么办？（更改默认超时时间没用，还会超时）

### ISSUE THREAD

**Issue by FranklinXu** [apolloconfig/apollo-build-scripts#46]
报错信息如下：
[root@localhost ~]# cd /usr/local
[root@localhost local]# cd apollo-build-scripts-master/
[root@localhost apollo-build-scripts-master]# ./demo.sh start
==== starting service ====
Service logging file is ./service/apollo-service.log
Started [3614]
Waiting for config service startup................................................
Config service failed to start in 120 seconds! Please check ./service/apollo-service.log for more information.
[root@localhost apollo-build-scripts-master]# 

demo.sh如下：

# apollo config db info
apollo_config_db_url=jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8
apollo_config_db_username=root
apollo_config_db_password=itcast

# apollo portal db info
apollo_portal_db_url=jdbc:mysql://localhost:3306/ApolloPortalDB?characterEncoding=utf8
apollo_portal_db_username=root
apollo_portal_db_password=itcast

# =============== Please do not modify the following content =============== #

if [ "$(uname)" == "Darwin" ]; then
    windows="0"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    windows="0"
elif [ "$(expr substr $(uname -s) 1 5)" == "MINGW" ]; then
    windows="1"
else
    windows="0"
fi

# meta server url
config_server_url=http://localhost:3306:8080
admin_server_url=http://localhost:3306:8090
eureka_service_url=$config_server_url/eureka/
portal_url=http://localhost:3306:8070

apollo-service.log如下：
2020-03-15 08:33:51.580  INFO 11712 --- [main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@2fdb53ff: startup date [Sun Mar 15 08:33:51 CST 2020]; root of context hierarchy
2020-03-15 08:33:55.400  INFO 11712 --- [main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2020-03-15 08:33:56.678  INFO 11712 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$3e9a029] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-03-15 08:33:58.026  INFO 11712 --- [main] c.c.f.apollo.assembly.ApolloApplication  : The following profiles are active: github
2020-03-15 08:33:58.166  INFO 11712 --- [main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@65c758c1: startup date [Sun Mar 15 08:33:58 CST 2020]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@2fdb53ff
2020-03-15 08:34:06.970  INFO 11712 --- [main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=acf2182f-e56e-3685-84a9-b4a19c8615a0
2020-03-15 08:34:07.172  INFO 11712 --- [main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2020-03-15 08:34:08.317  INFO 11712 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$3e9a029] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-03-15 08:34:09.110  WARN 11712 --- [main] o.s.c.n.a.ArchaiusAutoConfiguration      : No spring.application.name found, defaulting to 'application'
2020-03-15 08:34:09.316  WARN 11712 --- [main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2020-03-15 08:34:09.317  INFO 11712 --- [main] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2020-03-15 08:34:09.390  WARN 11712 --- [main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2020-03-15 08:34:09.390  INFO 11712 --- [main] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2020-03-15 08:34:11.449  INFO 11712 --- [main] o.s.l.c.support.AbstractContextSource    : Property 'userDn' not set - anonymous context will be used for read-write operations
2020-03-15 08:34:27.700  INFO 11712 --- [main] o.s.ui.freemarker.SpringTemplateLoader   : SpringTemplateLoader for FreeMarker: using resource loader [org.springframework.context.annotation.AnnotationConfigApplicationContext@65c758c1: startup date [Sun Mar 15 08:33:58 CST 2020]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@2fdb53ff] and template loader path [classpath:/templates/]
2020-03-15 08:34:30.237  INFO 11712 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2020-03-15 08:34:30.310  INFO 11712 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'environmentManager' has been autodetected for JMX exposure
2020-03-15 08:34:30.312  INFO 11712 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'refreshScope' has been autodetected for JMX exposure
2020-03-15 08:34:30.314  INFO 11712 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
2020-03-15 08:34:30.333  INFO 11712 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]
2020-03-15 08:34:30.433  INFO 11712 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.context.scope.refresh:name=refreshScope,type=RefreshScope]
2020-03-15 08:34:30.579  INFO 11712 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=65c758c1,type=ConfigurationPropertiesRebinder]
2020-03-15 08:34:30.641  INFO 11712 --- [main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2020-03-15 08:34:30.772  INFO 11712 --- [main] o.s.c.n.eureka.InstanceInfoFactory       : Setting initial instance status as: STARTING
2020-03-15 08:34:31.113  INFO 11712 --- [main] com.netflix.discovery.DiscoveryClient    : Initializing Eureka in region us-east-1
2020-03-15 08:34:33.788  INFO 11712 --- [main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
2020-03-15 08:34:33.791  INFO 11712 --- [main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
2020-03-15 08:34:34.971  INFO 11712 --- [main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
2020-03-15 08:34:34.972  INFO 11712 --- [main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
2020-03-15 08:34:36.039  INFO 11712 --- [main] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2020-03-15 08:34:36.164  INFO 11712 --- [main] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
2020-03-15 08:34:36.164  INFO 11712 --- [main] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
2020-03-15 08:34:36.164  INFO 11712 --- [main] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
2020-03-15 08:34:36.164  INFO 11712 --- [main] com.netflix.discovery.DiscoveryClient    : Application is null : false
2020-03-15 08:34:36.164  INFO 11712 --- [main] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
2020-03-15 08:34:36.165  INFO 11712 --- [main] com.netflix.discovery.DiscoveryClient    : Application version is -1: true
2020-03-15 08:34:36.165  INFO 11712 --- [main] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2020-03-15 08:34:36.821 ERROR 11712 --- [main] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error

com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: 拒绝连接 (Connection refused)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
	at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123)
	at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27)
	at com.sun.jersey.api.client.Client.handle(Client.java:652)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:509)

**Comment by nobodyiam** [comment]
看上去是启动比较慢？把max_counter调大些试试

https://github.com/nobodyiam/apollo-build-scripts/blob/7ebd3efdafa946ede6f723bb70d92aa9920449ca/demo.sh#L79

**Comment by Rockstics** [comment]
我也遇到过类似情况，最后是因为数据库的原因，请确认下你的数据库连接有没有问题

**Comment by wanghuashun** [comment]
一般数据库吧sql文件导入进去还需要注意什么那
