### ISSUE TITLE
dev环境异常是什么原因

### ISSUE THREAD

**Issue by zl214389366** [apolloconfig/apollo-build-scripts#53]
按照默认按照后：dev环境始终异常
日志错误：

2020-07-01 10:25:47.773 ERROR 43819 --- [Apollo-EnvHealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env health check failed, maybe because of meta server down or configure wrong meta server address. env: DEV, meta server address: http://192.168.73.132:8080

com.ctrip.framework.apollo.common.exception.ServiceException: Admin servers are unresponsive. meta server address: http://192.168.73.132:8080, admin servers: [ServiceDTO{appName='APOLLO-ADMINSERVICE', instanceId='192.168.73.132:apollo-adminservice:8090', homepageUrl='http://192.168.73.132:8090/'}]
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.execute(RetryableRestTemplate.java:122)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.get(RetryableRestTemplate.java:63)
	at com.ctrip.framework.apollo.portal.api.AdminServiceAPI$HealthAPI.health(AdminServiceAPI.java:27)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.isUp(PortalSettings.java:132)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.run(PortalSettings.java:108)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-07-01 10:25:47.775 ERROR 43819 --- [Apollo-EnvHealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env is down. env: DEV, failed times: 9, meta server address: http://192.168.73.132:8080

启动后一段时间，8080 自动就 挂掉了
![image](https://user-images.githubusercontent.com/28615961/86197474-06aa6c80-bb88-11ea-891c-84f8177e5542.png)

**Comment by zl214389366** [comment]
找到问题了，兼容性问题，windows  克隆的代码，在传到linux，不兼容
